backend:
  name: github
  repo: fogcity/fog-city-jazz
  branch: main
  base_url: https://fog-city-jazz.vercel.app
  site_domain: fog-city-jazz.vercel.app
  auth_endpoint: oauth

media_folder: "public/media"
public_folder: "/media"

editor:
  preview: false

collections:
  - name: pages
    label: Pages
    folder: "src/content/pages"
    extension: mdx
    format: frontmatter
    delete: false
    show_preview_links: false
    fields:
      - { label: Title, name: title, widget: "string" }
      - {
          label: Description,
          name: description,
          widget: "string",
          required: false,
        }
      - {
          label: Imports,
          name: setup,
          widget: hidden,
          default: "import ImageTextBlock from '@components/ImageTextBlock.astro'",
        }
      - { label: Body, name: body, widget: "markdown" }
